In [1]:
import numpy as np

In [2]:
benimDizim=np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizim[5]

5

In [6]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [7]:
benimDizim[3:8]= -5

In [8]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [9]:
baskaDizi=np.arange(0,24)

In [16]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [17]:
slicingDizisi=baskaDizi[4:9]

In [20]:
# slicingDizisi = 700 böyle olursa dizi int olur ve 700 e eşitlenir.
# slicingDizisi[:] =700 böyle olursa elemanları 700 ile değiştirilir.

In [21]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [22]:
baskaDizi #parçasını aldığımız orjinal dizi de değişmiş oldu

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [24]:
ornekDizi = np.arange(0,24)

In [32]:
#eğer .copy yaparsak orjinal dizi içindeki veriler değişmemiş olur
ornekDiziKopyasi= ornekDizi.copy()

In [33]:
ornekDiziKopyaSlicing=ornekDiziKopyasi[3:6]

In [34]:
ornekDiziKopyaSlicing[:]=756

In [35]:
ornekDiziKopyaSlicing

array([756, 756, 756])

In [36]:
ornekDiziKopyasi

array([  0,   1,   2, 756, 756, 756,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [37]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [38]:
benimListem=[[10,20,30],[20,30,40],[40,50,60]]

In [40]:
benimMatrixDizim=np.array(benimListem)

In [41]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [44]:
benimMatrixDizim[1][2]
#benimMatrixDizim[1,2] ile aynı şey

40

In [45]:
benimMatrixDizim[1:,2] #1 sütundan itibaren tamamı ama o sütunların 2.indexleri

array([40, 60])

In [47]:
benimMatrixDizim[1,0:]

array([20, 30, 40])

In [49]:
yeniListe=[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [50]:
yeniMatrix=np.array(yeniListe)

In [51]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
yeniMatrix[2]

array([10, 11, 12, 13, 14])

In [54]:
yeniMatrix[[4,2,0]] #4 üncü 2 inci ve 0 ıncı elemaları liste halinde getirdi

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

## operasyonlar

In [64]:
yeniBirDizi=np.random.randint(1,100,20)

In [65]:
yeniBirDizi

array([23, 85, 70, 69, 97, 71, 91, 21, 62, 24, 17, 11, 25, 15, 67, 69, 17,
       99, 69, 46])

In [72]:
yeniBirDizi>25

array([False,  True,  True,  True,  True,  True,  True, False,  True,
       False, False, False, False, False,  True,  True, False,  True,
        True,  True])

In [76]:
sonucDizisi=yeniBirDizi > 25

In [77]:
yeniBirDizi[sonucDizisi]

array([85, 70, 69, 97, 71, 91, 62, 67, 69, 99, 69, 46])

In [78]:
sonDizi=np.arange(0,24)

In [79]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [80]:
sonDizi+sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [81]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [82]:
sonDizi-sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [83]:
sonDizi/sonDizi

C:\Users\YALCIN~1\AppData\Local\Temp/ipykernel_12448/1954055075.py:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi/sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [84]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])