In [1]:
import numpy as np

## Numpy Array

In [2]:
benimListem=[20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem)

array([20, 30, 40])

In [6]:
matrixListesi=[[10,20,30],[20,30,40],[30,40,50]]

In [7]:
matrixListesi[0][1]

20

In [8]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## Numpy arange

In [9]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros and ones

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((8,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace


In [24]:
#start index ile stop index arasında eşit boşlukla dizi oluşturur.
#aşağıda 0 ile 10 arası toplam 10 sayılık dizi yaptı ve sayıların araları eşit

np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

## eye

In [27]:
#confisuon matrix gibi diyagonal olarak 1 yazdırır
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [36]:
np.random.randn(8)

array([ 1.13955383, -0.37273796,  0.41544043, -0.37549583, -0.32730327,
       -0.08124116,  1.25253267, -0.1957085 ])

In [39]:
np.random.randn(4,4)

array([[ 1.60158308,  0.58683934,  0.61501149, -1.30607379],
       [-0.42404854, -2.04314351,  0.1328117 ,  1.76517715],
       [ 2.64504695, -0.13528002,  0.59605528,  0.89366535],
       [ 0.53153065, -0.50578686, -0.02548793,  0.30636175]])

In [43]:
np.random.randint(1,10)

6

In [46]:
np.random.randint(1,100,5)

array([11, 56, 95, 35,  6])

In [47]:
benimNpDizim=np.arange(30)

In [48]:
benimNpDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [49]:
benimRandomDizim=np.random.randint(0,100,10)

In [51]:
benimRandomDizim

array([85, 52, 33, 55, 10, 63, 58, 91, 99, 93])

## numpy dizi methodları

In [55]:
#diziyi 6x5 luk matris yaptık reshape
benimNpDizim.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [56]:
benimNpDizim.max()

29

In [57]:
benimNpDizim.min()

0

In [58]:
benimNpDizim.mean()

14.5

In [63]:
#max sayınını kaçıncı indexte olduğunu yazar
benimRandomDizim.argmax()

8

In [64]:
#min sayınını kaçıncı indexte olduğunu yazar
benimRandomDizim.argmin()

4

In [67]:
reshapeDizim=benimNpDizim.reshape(5,6)

In [68]:
#dizinin şeklini yani boyutunu döndürür
reshapeDizim.shape

(5, 6)